import itemCap from './catalog-img/itemCap.png'

export const itemsCatalog = [
    {
        id: 1,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 2,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 3,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 4,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 5,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 6,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 7,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 8,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 9,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 10,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 11,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 12,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 13,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 14,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 15,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 16,
        image: { itemCap },
        name: 'Nike',
        price: '2300c',
        series: 'New York Yankies',
    },
    {
        id: 17,
        image: { itemCap },
        name: 'Nike 22',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 18,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 19,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 20,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 21,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 22,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 23,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 24,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 25,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 26,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 27,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 28,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 29,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 30,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 31,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 32,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 33,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 34,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 35,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 36,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 37,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 38,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 39,
        image: { itemCap },
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 40,
        image: { itemCap },
        name: 'Nike',
        price: '32c',
        series: 'New York Yankies',
    },
]
