import itemCap from './catalog-img/itemCap.png'

export const itemsCatalog = [
    {
        id: 1,
        image: {itemCap},
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 2,
        image: {itemCap},
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 3,
        image: {itemCap},
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 4,
        image: {itemCap},
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 5,
        image: {itemCap},
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 6,
        image: {itemCap},
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 7,
        image: {itemCap},
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 8,
        image: {itemCap},
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 9,
        image: {itemCap},
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 10,
        image: {itemCap},
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 11,
        image: {itemCap},
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 12,
        image: {itemCap},
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 13,
        image: {itemCap},
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 14,
        image: {itemCap},
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    },
    {
        id: 15,
        image: {itemCap},
        name: 'Nike',
        price: '3200c',
        series: 'New York Yankies',
    }
]
